name: Create release and attach ngstoolkitdist.tar

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Create Release
    runs-on: high-cpu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker version
      run: docker --version
    - name: Pipeline version
      run: python3 -m ngspipeline.cli --version
    - name: Build and export ngstoolkitdist
      run: python3 -m ngspipeline.cli --export
    - name: Cleanup pycache
      run: find -type d -name "__pycache__" | xargs rm -r
    - name: Create archive
      run: git archive --format=zip -o release.zip -9 HEAD
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: false
        files: |
          release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
