name: Build and attach ngstoolkitdist.tar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: high-cpu

    steps:
    - uses: actions/checkout@v2
    - name: Docker version
      run: docker --version
    - name: Pipeline version
      run: python3 -m ngspipeline.cli --version
    - name: Build and export ngstoolkitdist
      run: python3 -m ngspipeline.cli --export
    - name: Archive distribution artifact
      uses: actions/upload-artifact@v2
      with:
        name: ngstoolkitdist.tar
        path: ngstoolkitdist.tar
