name: Check dependencies

on:
  schedule:
    - cron: "14 17 * * *"
    
jobs:
  check-sortmeRNA:
    runs-on: ubuntu-latest
    name: Check for new releases of sortmeRNA
    env:
      DOCKERFILE: "wsl_distro_build/build-context/Dockerfile"
      REPO: "biocore/sortmerna"
    steps:
    - name: Get sortmeRNA version from Dockerfile
      run: echo "USED_VERSION=$(grep "sortmerna_version=" ${DOCKERFILE} | cut -f2 -d'"')" >> $GITHUB_ENV
    - name: Get current version from github
      run: echo "LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${REPO}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV
    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ v${USED_VERSION} == ${LATEST_VERSION} }}
      name: Create issue when new version is available
      with:
        title: Update sortmeRNA to release version ${CURRENT_VERSION}
        token: ${{secrets.GITHUB_TOKEN}}
        labels: dependency-update
        body: A new release of ${REPO} was found. Dockerfile uses version v${USED_VERSION} but latest available version is ${LATEST_VERSION}.
